name: deeplook3
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.5
    - pip
    - numpy
    - scipy
    - future
    - matplotlib
    - scikit-learn
    - pep8
    - coverage
    - pytest
    - pytest-cov
    - sphinx
    - sphinx_rtd_theme
    - jupyter
    - pip:
        - sphinx-gallery
