name: deeplook3
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.6
    - pip
    - numpy
    - scipy
    - future
    - matplotlib
    - scikit-learn
    - flake8
    - pylint
    - coverage
    - pytest
    - pytest-cov
    - sphinx
    - sphinx_rtd_theme
    - jupyter
    - sphinx-gallery
